export enum SignatureStatus {
  PENDING = 'WAITING_LOCAL_ACK',
  WAITING = 'NOT_READY',
  TIMEOUT = 'TIMEOUT',
  SUCCESS = 'SUCCESS',
  USER_CANCELLED = 'USER_CANCELLED',
  RP_CANCELLED = 'RP_CANCELLED',
  ACCOUNT_NOT_VERIFIED = 'NOT_VERIFIED',
  ACCOUNT_FOUND = 'ACCOUNT_FOUND',
  ACCOUNT_NOT_FOUND = 'ACCOUNT_NOT_FOUND',
  INVALID_EID_RESPONSE = 'INVALID_EID_RESPONSE'
}

export type AuthEidStatusData = {
  status: SignatureStatus;
};
